export const items = ref([
  {
    id: 1,
    date: '19/11/2023',
    type: 'ingreso',
    concept: 'Comidas Ricardo',
    price: 1000,
    category: 'Venta',
    ticket: '',
  },
  {
    id: 2,
    date: '19/11/2023',
    type: 'gasto',
    concept: 'Insumos 19/11/2023',
    price: 616,
    category: 'Insumos',
    ticket: '',
  },
  {
    id: 3,
    date: '19/11/2023',
    type: 'gasto',
    concept: 'Pago Aby 19/11/2023',
    price: 700,
    category: 'Sueldo',
    ticket: '',
  },
  {
    id: 4,
    date: '19/11/2023',
    type: 'ingreso',
    concept: '',
    price: 0,
    category: '',
    ticket: '',
  },
  {
    id: 5,
    date: '19/11/2023',
    type: 'gasto',
    concept: '',
    price: 0,
    category: '',
    ticket: '',
  },
]);
